# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: project.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rproject.proto\x12\x07project\"\x1f\n\x0bHeadRequest\x12\x10\n\x08userHead\x18\x01 \x01(\t\"\x1c\n\x0cHeadResponse\x12\x0c\n\x04head\x18\x01 \x01(\t\"\x1b\n\x0b\x42logRequest\x12\x0c\n\x04head\x18\x01 \x01(\t\"*\n\x0c\x42logResponse\x12\x0c\n\x04head\x18\x01 \x01(\t\x12\x0c\n\x04\x62log\x18\x02 \x01(\t\"/\n\x0e\x43ommentRequest\x12\x0f\n\x07\x63omment\x18\x01 \x01(\t\x12\x0c\n\x04head\x18\x02 \x01(\t\"\x1e\n\x0f\x43ommentResponse\x12\x0b\n\x03\x61\x64\x64\x18\x01 \x01(\x08\"\x1a\n\nOneRequest\x12\x0c\n\x04user\x18\x01 \x01(\t\")\n\x0bOneResponse\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x0c\n\x04\x66ind\x18\x02 \x01(\x08\"\x1b\n\x0bViewRequest\x12\x0c\n\x04\x66ind\x18\x01 \x01(\x08\"\x1c\n\x0cViewResponse\x12\x0c\n\x04user\x18\x01 \x01(\t\"%\n\x12\x43redentialsRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"%\n\x13\x43redentialsResponse\x12\x0e\n\x06logged\x18\x01 \x01(\x08\x32Y\n\x0cLogInService\x12I\n\nCheckLogIn\x12\x1b.project.CredentialsRequest\x1a\x1c.project.CredentialsResponse\"\x00\x32\x8a\x01\n\x0fSearcherService\x12\x38\n\tSearchOne\x12\x13.project.OneRequest\x1a\x14.project.OneResponse\"\x00\x12=\n\nSearchView\x12\x14.project.ViewRequest\x1a\x15.project.ViewResponse\"\x00\x30\x01\x32\xc9\x01\n\x06reader\x12@\n\rviewHeadlines\x12\x14.project.HeadRequest\x1a\x15.project.HeadResponse\"\x00\x30\x01\x12\x39\n\x08showBlog\x12\x14.project.BlogRequest\x1a\x15.project.BlogResponse\"\x00\x12\x42\n\x0b\x63ommentBlog\x12\x17.project.CommentRequest\x1a\x18.project.CommentResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'project_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HEADREQUEST._serialized_start=26
  _HEADREQUEST._serialized_end=57
  _HEADRESPONSE._serialized_start=59
  _HEADRESPONSE._serialized_end=87
  _BLOGREQUEST._serialized_start=89
  _BLOGREQUEST._serialized_end=116
  _BLOGRESPONSE._serialized_start=118
  _BLOGRESPONSE._serialized_end=160
  _COMMENTREQUEST._serialized_start=162
  _COMMENTREQUEST._serialized_end=209
  _COMMENTRESPONSE._serialized_start=211
  _COMMENTRESPONSE._serialized_end=241
  _ONEREQUEST._serialized_start=243
  _ONEREQUEST._serialized_end=269
  _ONERESPONSE._serialized_start=271
  _ONERESPONSE._serialized_end=312
  _VIEWREQUEST._serialized_start=314
  _VIEWREQUEST._serialized_end=341
  _VIEWRESPONSE._serialized_start=343
  _VIEWRESPONSE._serialized_end=371
  _CREDENTIALSREQUEST._serialized_start=373
  _CREDENTIALSREQUEST._serialized_end=410
  _CREDENTIALSRESPONSE._serialized_start=412
  _CREDENTIALSRESPONSE._serialized_end=449
  _LOGINSERVICE._serialized_start=451
  _LOGINSERVICE._serialized_end=540
  _SEARCHERSERVICE._serialized_start=543
  _SEARCHERSERVICE._serialized_end=681
  _READER._serialized_start=684
  _READER._serialized_end=885
# @@protoc_insertion_point(module_scope)
